version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Building the application...
  build:
    commands:
      - echo Build completed on `date`
      - aws s3 cp . s3://tylerfresume/ --recursive

  post_build:
    commands:
      - echo Creating CloudFront Invalidation
      - aws cloudfront create-invalidation --distribution-id EMTJQND3ELN13 --paths '/*'

artifacts:
  files:
    - '**/*'
  discard-paths: yes

  include:
    - 'iam/**'
    - 'images/**'
    - 'js/**'