version: 0.2
phases:
  build:
    commands:
      - aws s3 cp . s3://tylerfresume/ --recursive
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id EMTJQND3ELN13 --paths '/*'
artifacts:
  files:
    - '**/*'